us-04-autenticação
FeudoAmareloGirassol/FeudoAmareloGirassol pull request #38
Opened 2022-03-20 07:10 UTC by chaydson

## Descrição
Descrição simples e concisa de como o pr resolve um problema.
Esse pull request cria a API responsável pelo registro e autenticação de clientes e empresas, assim como, integra a API com o front-end.
soluciona issue #8

Tarefas gerais realizadas:
* Desenvolvimento da API que realiza cadastro e autenticação dos usuários.
* Criação dos formulários no front-end responsáveis pelo login e registro dos usuários.
* Instauração da conexão entre a API e os formulários do angular.

2022-03-20 14:26 UTC, andrelucax commented on backend/project/markit/settings.py
> +# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/
Voces trocaram a versão do django? creio que no requirements esteja 4.0 ainda, entao nao vejo pq mudar o comentario

2022-03-20 14:28 UTC, andrelucax commented on backend/project/markit/settings.py
> +# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/
se tiver trocado a versao tem q mudar o requirements tb, (verificar outros comentarios c a msm coisa)

2022-03-20 14:31 UTC, andrelucax commented on frontend/frontendAngular/angular.json
> +              "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
creio q essa linha nao esteja fznd nd

2022-03-20 14:31 UTC, andrelucax commented on frontend/frontendAngular/angular.json
> +              "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
creio q essa linha nao esteja fznd nd

2022-03-20 14:36 UTC, andrelucax commented on backend/project/markit/settings.py
> +    'rest_framework_simplejwt',
voces adicionaram depencencia nova mas nao colocaram no requirements.txt

2022-03-20 14:45 UTC, andrelucax commented on backend/project/users/views.py
> +        userSerializer = UserSerializer(data=request.data['user'])
Creio que para esse caso nao precisamos acessar ['user'] o request pode ser direto

2022-03-20 14:46 UTC, andrelucax commented on backend/project/users/views.py
> +        companySerializer = CompanySerializer(data=request.data['company'])
request.data[...] pode gerar exception caso o request não venha como você quer, não é ter exceção sem tratamento

2022-03-20 14:49 UTC, andrelucax commented on backend/project/users/views.py
> +    def perform_create(self, serializer):
creio que seja desnecessário esse código

2022-03-20 15:27 UTC, andrelucax requested changes
Arrumar conflitos e comentarios

2022-03-20 15:27 UTC, andrelucax commented on backend/project/users/views.py
> +        companySerializer.is_valid(raise_exception=True)
creio que o retorno de erro poderia ser melhor pra esse caso que recebe mais de uma coisa, deixando mais intuitivo o erro
```
errors = {}
if not userSerializer.is_valid():
    errors['user'] = userSerializer.errors
if not companySerializer.is_valid():
    errors['comapny'] = companySerializer.errors
if errors:
    return Response(errors)
```

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/api/company.ts
> +    user: CustomerBase
creio que a interface deveria ser CustomerRequest visto que está dentro de outro request

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/api/customer.ts
> +export interface CustomerModel extends CustomerBase{
tira todas as interfaces q tiver base, separa o Model do Request mesmo que repita os campos, creio que ficará melhor

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/app-routing.module.ts
> +      path: 'user-view',
talvez user/home seria melhor

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/login/login.component.ts
> +      var obj = JSON.stringify(response, ['access']);
creio q nao seja necessario usar o JSON.stringify... se vc for no loginService e definir o retorno do post `...post<LoginResponse>(...` criando a interface LoginResponse seja melhor

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/login/login.component.ts
> +      this.isLoading = false;
creio que podemos redirecionar pra tela de usuario logado apos login tb

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/login/login.component.ts
> +      console.log("Logged", response);
tirar todos os console.log( ... raramente um console.log vai estar em algum PR

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/navbar/navbar.component.html
> +    <ng-container *ngIf="router.routerState.snapshot.url == '/user-view'">
Creio que deva ser um pouco diferente o if pra saber se a pessoa ta logada ou nao, ela pode estar em outra rota q nao seja essa

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/navbar/navbar.component.html
> +  <mat-toolbar color="primary" class="header">
a gnt usa o bootstrap conversar com o @PedroHenrique2077 e pedir dicas

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/navbar/navbar.component.ts
> +  constructor(public router: Router, private localStorage: LocalStorageLoginService) { }
quebrar as linhas do construtor quando houver mais do q 1 parametro
```
constructor(
...
)
```

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/register-company/register-company.component.ts
> +    private snackBService:MessageService) {
creio q seja melhor utulizar o nome do service q vc criou mesmo... messageService: MessageService

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/register-company/register-company.component.ts
> +    let senha1 = <String>this.form.controls['password'].value;
realmente é necessário o typecast?

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/register-company/register-company.component.ts
> +      this.form.controls['password'].value == this.form.controls['confirm_password'].value &&
essa validação nao existe no backend, ou coloca la ou retira daqui... o front é um espelho do back, precisa das mesmas validações

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/register-company/register-company.component.ts
> +      this.isLoading = false;
Creio que ele possa ser redirecionado pra tela de login ou home de usuario apos o login, o que preferir

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/register-customer/register-customer.component.ts
> +    private snackBService:MessageService
messageService

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/register-customer/register-customer.component.ts
> +    let senha1 = <String>this.form.controls['password'].value;
precisa typecast?

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/register-customer/register-customer.component.ts
> +    this.form.controls['password'].value == this.form.controls['confirm_password'].value &&
validação nao existe no back

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/register-customer/register-customer.component.ts
> +      this.isLoading = false;
redirect

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/user-view/user-view.component.ts
> +export class UserViewComponent implements OnInit {
melhor UserHome

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/guards/login.guard.ts
> +  constructor(public localStorage: LocalStorageLoginService, private router: Router){}
quebra d linha do construtor

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/guards/login.guard.ts
> +    if(!this.localStorage.logged){
creio que conseguimos usar o get que voces mesmos criaram pra verificar se o usuario ta logado ou nao... e remover o logged to service... ou fazer o logged do service usar o get

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/services/authentication.service.ts
> +    return this.http.post(`${apiUrl}`, request)
essa função tem retorno no backend... colocar a interface do retorno dela

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/services/local-storage-login.service.ts
> +    return this.storage.getItem('token') ? true : false
user get previamente criado ou remover essa função e usar o get no guard

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/services/message-service.service.ts
> +export class MessageService {
creio que qualquer mensagem ficaria melhor no superior direito da tela invés de aparecer em baixo no meio

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/services/message-service.service.ts
> +  showSuccess(message: string, action: string) {
creio que poderia ter a color success

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/services/message-service.service.ts
> +    this._snackBar.open(message, action, {
creio que poderia ter a color de error

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/app/services/message-service.service.ts
> +  showWarning(message: string, action: string) {
creio que poderia ter color de warning

2022-03-20 15:27 UTC, andrelucax commented on frontend/frontendAngular/src/index.html
> +  <link rel="preconnect" href="https://fonts.gstatic.com">
nao vejo pq dessas fontes. remover 3 links

2022-03-21 13:02 UTC, andrelucax commented on frontend/frontendAngular/src/app/app-routing.module.ts
> +import { LoginGuard } from './guards/login.guard';
Talvez AuthenticatedGuard seja melhor

2022-03-21 13:34 UTC, chaydson commented on frontend/frontendAngular/src/app/api/company.ts
> +    user: CustomerBase
Já existe um CustomerRequest com outra função. Acho que pode gerar confusão ter dois requests com nomes iguais fazendo coisas diferentes.

2022-03-21 13:47 UTC, chaydson commented on frontend/frontendAngular/src/app/api/customer.ts
> +export interface CustomerModel extends CustomerBase{
o User da interface CustomerRequest e CompanyRequest estão utilizando a base e não sabemos como fazer sem ela.

2022-03-21 21:54 UTC, chaydson commented on backend/project/users/views.py
> +        userSerializer = UserSerializer(data=request.data['user'])
no meu teste deu erro quando eu tirei

2022-03-22 01:15 UTC, andrelucax commented on backend/project/users/views.py
> +        userSerializer = UserSerializer(data=request.data['user'])
@chaydson refaça o teste de novo... vc está passando um JSON `{ "user": ...data }` é só passar `{ ...data }`

2022-03-22 01:28 UTC, andrelucax commented on backend/project/users/views.py
> +        companySerializer = CompanySerializer(data=request.data['company'])
@chaydson continua podendo gerar exceção aqui, não foi corrigido... caso vc tente acessar uma chave que não foi definida no dicionario do python ele vai dar exceção... podemos criar um serializer pra esse registro
```
class CompanyRegisterSerializer(serializers.Serializer):
    user = UserSerializer
    company = CompanySerializer
```
com isso podemos verificar direto

2022-03-22 01:29 UTC, andrelucax commented on backend/project/users/views.py
> +        companySerializer = CompanySerializer(data=request.data['company'])
creio que com isso conseguimos paramos de usar 2 serializer, pegando na mao do dicionario, e tendo que verificar a validade de 2...

2022-03-22 01:30 UTC, andrelucax commented on frontend/frontendAngular/src/app/api/company.ts
> +    user: CustomerBase
perdão, acho que me expressei errado... CustomerBase deveria ser CustomerRequest

2022-03-22 01:32 UTC, andrelucax commented on frontend/frontendAngular/src/app/api/customer.ts
> +export interface CustomerModel extends CustomerBase{
é só ambos terem os mesmos campos... (ficando duplicado mesmo) mas eles um request e um response (model) sao conceitualmente diferentes, é estranho ambos herdarem de alguem

2022-03-22 01:52 UTC, andrelucax requested changes
Corrigir os comentarios

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/api/customer.ts
> +export interface CustomerBase{
Essa interface deveria se chamar CustomerRequest

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/api/login.ts
> +export interface loginResponse extends loginResponseBase{
Maiusculo

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/api/login.ts
> +export interface loginResponseBase{
creio que nao seja necessario esse base e LoginResponse poderia ter os 3 campos

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/navbar/navbar.component.css
> +.settings:hover{
creio ser desnecessario

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/navbar/navbar.component.css
> +a{
creio que seja melhor criar uma classe pra isso, futuramente pode ter outras tags 'a' que nao terão esse estilo dentro do navbar

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/navbar/navbar.component.html
> +      <span style="margin-left: 1250px;">
https://material.angular.io/components/button/examples

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/navbar/navbar.component.ts
> +    this.messageService.showSuccess("Registrado com sucesso", "Ok", 'success-snackbar');
estranho ter q passar o 'success-snackbar' dentro do showSuccess... essa função ja deveria saber qual estilo deve seguir

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/register-company/register-company.component.ts
> +      this.messageService.showError("Senhas diferentes", "Ok", "error-snackbar");
funcao estranha

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/register-company/register-company.component.ts
> +      this.form.controls['password'].value == this.form.controls['confirm_password'].value &&
Creio ter me expressado mal novamente, peço-te desculpas, estava a falar da validação do tamanho de senha e não do confirm_password

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/register-customer/register-customer.component.ts
> +    this.form.controls['password'].value == this.form.controls['confirm_password'].value &&
tamanho das senhas nao confirm_password

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/api/customer.ts
> +    confirm_password: string;
não precisa mandar o confirmPassword..

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/register-company/register-company.component.ts
> +    let senha1 = this.form.controls['password'].value;
portugues?

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/register-company/register-company.component.ts
> +        confirm_password:this.form.controls['password'].value,
n precisa mandar confirmPassword

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/register-customer/register-customer.component.ts
> +    let senha1 = this.form.controls['password'].value;
portugues?

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/register-customer/register-customer.component.ts
> +        confirm_password:this.form.controls['password'].value,
n precisa mandar o confirmPassword

2022-03-22 01:52 UTC, andrelucax commented on backend/project/users/serializers.py
> +        if password == confirm_password:
sem confirm password

2022-03-22 01:52 UTC, andrelucax commented on backend/project/users/serializers.py
> +        confirm_password = validated_data.pop('confirm_password', None)
sem confirmPass

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/components/navbar/navbar.component.html
> +    <span><a href="/user/home">Mark.it</a></span>
não usamos href no angular... perguntar pro @pedro o motivo

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/guards/authenticated.guard.ts
> +    ){}
identação

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/services/message-service.service.ts
> +  showError(message: string, action: string, className:string) {
essa função nao recebe a class, ela já sabe quem é a classe

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/services/message-service.service.ts
> +  showSuccess(message: string, action: string, className:string) {
essa função nao recebe a class, ela já sabe quem é a classe

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/app/services/message-service.service.ts
> +  showWarning(message: string, action: string, className:string) {
essa função nao recebe a class, ela já sabe quem é a classe

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/index.html
> +  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
nao precisa desses links da google

2022-03-22 01:52 UTC, andrelucax commented on frontend/frontendAngular/src/styles.scss
> +    background: #a09d0d;
não sei se é o melhor jeito de trabalhar com as cores, vou pensar dps

2022-03-22 01:55 UTC, andrelucax commented
@PedroHenrique2077 te marquei como revisor, após o @chaydson arrumar os comentários que eu fiz vou deixar você fzr a próxima revisão já trabalhando na sua isse de integrar o back com o front

2022-04-02 22:14 UTC, andrelucax commented
foi anexada em outro PR

2022-04-02 22:14 UTC, closed without merging