US-30 View User
FeudoAmareloGirassol/FeudoAmareloGirassol pull request #40
Opened 2022-03-20 15:52 UTC by CarolinaBarb

Co-authored-by: Ana Luiza<211030676@aluno.unb.br>

## Descrição
Criar tela inicial do view user com dados mockados e criar componentes para o  view user e o para os cards.

soluciona issue #30

Tarefas gerais realizadas:

* Criamos o componente do view user.
* Criamos o componente do card view user.
* Utilizamos dados mockados na tela do view user.

2022-03-20 17:07 UTC, andrelucax commented
@chaydson te marquei como revisor, aproveitar que tu vai dar continuidade na issue pra revisar ela

2022-03-26 19:59 UTC, chaydson requested changes

2022-03-26 19:59 UTC, chaydson commented on frontend/frontendAngular/src/app/services/view-user.service.ts
> +  addCategoria(categoria: Categoria): Observable<Categoria> {
Não consegui adicionar uma categoria

2022-03-26 19:59 UTC, chaydson commented on frontend/frontendAngular/src/app/components/search/search.component.ts
> +  categorias$!:   Observable<Categoria[]>;
não consegui pesquisar as categorias adicionadas

2022-03-26 19:59 UTC, chaydson commented on frontend/frontendAngular/src/app/components/dashboard/dashboard.component.html
> +<div class="categorias-menu">
não há como acessar a parte de adicionar categorias sem ser colocando a url

2022-04-03 00:28 UTC, merged