Refactored back
FeudoAmareloGirassol/FeudoAmareloGirassol pull request #45
Opened 2022-04-05 23:37 UTC by chaydson

## Descrição
Refatora o backend.

resolve #44 

Tarefas gerais realizadas:
* Correção dos nomes das funções/classes/variaveis/etc
* Revisão do back-end
* Remoção dos elementos que não estavam mais sendo usados
* Remoção das duplicações

2022-04-08 23:25 UTC, andrelucax requested changes

2022-04-08 23:25 UTC, andrelucax commented on backend/project/users/urls.py
> +    path('get/', include(router.urls))
a rota api/get/(users | company) não faz o menor sentido)

2022-04-08 23:25 UTC, andrelucax commented on backend/project/users/views.py
>  class CompanyFilterView(generics.ListAPIView):
Não faz sentido ter 2 rotas pra filtro... deveria ser 1 rota apenas que faz os 2 filtros

2022-04-08 23:25 UTC, andrelucax commented on backend/project/users/views.py
>  class GetUsersViewset(viewsets.ModelViewSet):
Não creio que deveria exister um users ViewSet... precisamos apenas mostrar as categorias e nao os usuarios

2022-04-08 23:25 UTC, andrelucax commented on backend/project/users/views.py
>  class GetCompanyViewset(viewsets.ModelViewSet):
temos 3 rotas pra mostrar as company?? 1 pra filtrar nome, 1 pra filtrar categoria, 1 pra mostrar td? pq? deveria ser só 1

2022-04-08 23:25 UTC, andrelucax commented on backend/project/users/router.py
>  router.register(r'company', GetCompanyViewset)
companies

2022-04-08 23:25 UTC, andrelucax commented on backend/project/users/serializers.py
> +class GetUserSerializer(serializers.ModelSerializer):
Não existe serializer pra pegar os users

2022-04-08 23:25 UTC, andrelucax commented on backend/project/users/serializers.py
> +class RegisterCompanySerializer(serializers.ModelSerializer):
Realmente é necessário ter 1 Register Company serializer e um get company serializer? eles estão serializando a msm classes e retornando os mesmos atributos

2022-04-08 23:25 UTC, andrelucax commented on backend/project/users/serializers.py
>      @classmethod
"token['company'] = user.company" sempre vai dar nulo quando chegar nesse except...

2022-04-08 23:25 UTC, andrelucax commented on backend/project/users/views.py
>          if not userSerializer.is_valid():
class RegisterCustomerView(APIView):
  permission_classes = [AllowAny]
      def post(self, request):
          userSerializer = UserSerializer(data=request.data['user'])

data deveria ser request.data apenas...

Você está passando um json no formato { "user": { ...userData } } quando deveria ser apenas { ...userData }

2022-04-08 23:25 UTC, andrelucax commented on backend/project/users/models.py
> +    ('ASSISTENCIA_TECNICA', 'Assistência Técnica'),
colocar os campos em ingles....
('TECHNICAL_ASSISTANCE', "Assistência Técnica")

2022-04-11 23:12 UTC, chaydson commented on backend/project/users/serializers.py
> +class RegisterCompanySerializer(serializers.ModelSerializer):
Creio que sim pois para fazer o registro eu preciso passar o valor da categoria inglês e tudo maiúsculo, já para retornar os valores eu preciso que o valor da categoria esteja em português. Sendo assim, só vejo como resolução usar serializers diferentes para cada situação

2022-04-14 16:01 UTC, LucasLopesFrazao requested changes

2022-04-14 16:01 UTC, LucasLopesFrazao commented on backend/project/users/views.py
>          return Response({
Se você passar essas chaves no return Response, ele dá um Exception, favor apagar essas chaves.

2022-04-14 16:11 UTC, LucasLopesFrazao approved these changes

2022-04-14 16:17 UTC, andrelucax approved these changes
PR foi revisado pelo @LucasLopesFrazao, não estou revisando novamente

2022-04-14 17:08 UTC, merged