Schedule
FeudoAmareloGirassol/FeudoAmareloGirassol pull request #47
Opened 2022-04-10 14:18 UTC by LucasLopesFrazao

## Descrição
PR realiza os agendamentos, bem como também mostra esses agendamentos feitos tanto para o próprio User, quanto para a company.

soluciona issue #36

Tarefas gerais realizadas:
* User consiga fazer um agendamento em uma empresa X.
* User consiga vê os agendamentos feitos por ele mesmo.
* Company possa ver os agendamentos feitos na empresa dela.

2022-04-11 18:57 UTC, chaydson requested changes

2022-04-11 18:57 UTC, chaydson commented on backend/project/users/migrations/0001_initial.py
> +# Generated by Django 4.0.2 on 2022-04-05 01:23
por que vc mudou a versão do django?

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/dialog/dialog.component.ts
>  import { APIGETService } from 'src/app/services/api-get.service';
substituir src e app por ..

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/dialog/dialog.component.ts
>    onNoClick(): void {
não era pra ser onClick?

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/services/scheduling-register-service.service.ts
> +    private lsls: LocalStorageLoginService
colocar localStorage no lugar de lsls

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.ts
> +import { SchedulingRegisterServiceService } from 'src/app/services/scheduling-register-service.service';
substituir src e app por ..

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.ts
> +  schedulings : any = [];
Não deve ter nenhuma variável de tipo any, relacionar a respectiva interface

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.ts
> +  company : any = [];
Não deve ter nenhuma variável de tipo any, relacionar a respectiva interface

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.ts
> +            console.log(company)
remover console log

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.ts
> +            console.log(error)
remover console log

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.ts
> +        console.log(error)
remover console log

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.html
> +      <th scope="col">ID</th>
retirar ID

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> +import { SchedulingRegisterServiceService } from 'src/app/services/scheduling-register-service.service';
substituir src e app por ..

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> +        console.log(data)
retirar o console log

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> +        console.log(error)
retirar o console log

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.scss
> +.teste{
classe teste não é usada em lugar nenhum

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> +import { GetUsersService } from 'src/app/services/get-users.service';
substituir src e app por ..

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> +            console.log(error)
remover console log

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> +        console.log(error);
remover console log

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/dialog/dialog.component.html
> +      <mat-dialog-actions style="margin-left: 25%;">
criar uma classe para remover inline css

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/user-home/user-home.component.ts
> +      height: '500px',
teria como colocar outra medida sem ser px para adicionar responsividade ao dialog

2022-04-11 18:57 UTC, chaydson commented on frontend/frontendAngular/src/app/components/dialog/dialog.component.html
> +          <input matInput class="a" type="time" formControlName="SchedulingHour" #time>
o nome da classe é pouco explicativo, favor renomear

2022-04-11 18:57 UTC, PedroHenrique2077 requested changes

2022-04-11 18:57 UTC, PedroHenrique2077 commented on frontend/frontendAngular/src/app/components/dialog/dialog.component.html
> +      <form class="example-form" [formGroup]="SchedulingForm">
Aparamente essa "class = example-form" não esta sendo usada, caso esteja pfv alterar o nome para algo mais especifico.

2022-04-11 18:57 UTC, PedroHenrique2077 commented on frontend/frontendAngular/src/app/components/dialog/dialog.component.ts
> +    console.log(this.SchedulingForm.value);
pfv remover console.log

2022-04-11 18:57 UTC, PedroHenrique2077 commented on frontend/frontendAngular/src/app/services/scheduling-register-service.service.ts
> +export class SchedulingRegisterServiceService {
Pfv altere o nome dessa classe por conta do Service dobrado

2022-04-11 18:57 UTC, PedroHenrique2077 commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.html
> +      <th scope="col">ID</th>
pfv retire o ID da empresa

2022-04-11 18:57 UTC, PedroHenrique2077 commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.ts
> +    private SchedulingRegisterService: SchedulingRegisterServiceService,
Ao instanciar suas classes Service deve-se começar com letras minúsculas.

2022-04-11 18:57 UTC, PedroHenrique2077 commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.ts
> +    private GetCompanyService: GetCompanyService,
mesma coisa

2022-04-11 18:57 UTC, PedroHenrique2077 commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> +    private SchedulingRegisterService: SchedulingRegisterServiceService,
Ao instanciar começa com letra minúscula

2022-04-11 18:57 UTC, PedroHenrique2077 commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> +  schedulings : any = [];
remover o any e tipar o tipo de interface

2022-04-11 18:57 UTC, PedroHenrique2077 commented on frontend/frontendAngular/src/app/components/dialog/dialog.component.html
> +        <mat-form-field class="example-full-width">
apagar a classe se não estiver usando, caso esteja renomear para algo mais especifico.

2022-04-11 18:57 UTC, PedroHenrique2077 commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> -  schedulings : any = [];
remover o any

2022-04-12 10:41 UTC, LucasLopesFrazao commented on backend/project/users/migrations/0001_initial.py
> +# Generated by Django 4.0.2 on 2022-04-05 01:23
Esse arquivo é gerado automaticamente na hora que faz o makemigrations e o migrate, não faço a mínima ideia do porquê ele mudou a versão sozinho do Django ai...

2022-04-12 10:46 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/dialog/dialog.component.ts
>    onNoClick(): void {
Ok

2022-04-12 10:46 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/services/scheduling-register-service.service.ts
> +    private lsls: LocalStorageLoginService
Ok

2022-04-12 13:44 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.ts
> +  schedulings : any = [];
ok

2022-04-12 13:44 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.ts
> +  company : any = [];
ok

2022-04-12 13:45 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.ts
> +            console.log(company)
ok

2022-04-12 13:45 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.ts
> +            console.log(error)
ok

2022-04-12 13:45 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.ts
> +        console.log(error)
ok

2022-04-12 13:46 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.html
> +      <th scope="col">ID</th>
ok

2022-04-12 13:46 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> +        console.log(data)
ok

2022-04-12 13:47 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> +        console.log(error)
ok

2022-04-12 13:47 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.scss
> +.teste{
ok

2022-04-12 13:47 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> +            console.log(error)
ok

2022-04-12 13:47 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> +        console.log(error);
ok

2022-04-12 13:49 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/dialog/dialog.component.html
> +      <mat-dialog-actions style="margin-left: 25%;">
ok

2022-04-12 13:50 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/user-home/user-home.component.ts
> +      height: '500px',
Eu tinha feito com % anteriormente, porém depois depois que o andré juntou as 3 issues em uma, *Eu acho* que ele alterou para px, então eu acho melhor deixar do jeito que está.

2022-04-12 13:51 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/dialog/dialog.component.html
> +          <input matInput class="a" type="time" formControlName="SchedulingHour" #time>
ok

2022-04-12 13:53 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/dialog/dialog.component.html
> +      <form class="example-form" [formGroup]="SchedulingForm">
ok

2022-04-12 13:53 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/dialog/dialog.component.ts
> +    console.log(this.SchedulingForm.value);
ok

2022-04-12 13:54 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/services/scheduling-register-service.service.ts
> +export class SchedulingRegisterServiceService {
ok

2022-04-12 13:57 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.html
> +      <th scope="col">ID</th>
ok

2022-04-12 14:00 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.ts
> +    private SchedulingRegisterService: SchedulingRegisterServiceService,
ok

2022-04-12 14:00 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.ts
> +    private GetCompanyService: GetCompanyService,
ok

2022-04-12 14:01 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> +    private SchedulingRegisterService: SchedulingRegisterServiceService,
ok

2022-04-12 14:25 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> +  schedulings : any = [];
OK

2022-04-12 14:28 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/dialog/dialog.component.html
> +        <mat-form-field class="example-full-width">
ok

2022-04-12 14:28 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> -  schedulings : any = [];
ok

2022-04-12 14:31 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/dialog/dialog.component.ts
>  import { APIGETService } from 'src/app/services/api-get.service';
ok

2022-04-12 14:32 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/customer-schedule/customer-schedule.component.ts
> +import { SchedulingRegisterServiceService } from 'src/app/services/scheduling-register-service.service';
ok

2022-04-12 14:32 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> +import { SchedulingRegisterServiceService } from 'src/app/services/scheduling-register-service.service';
ok

2022-04-12 14:32 UTC, LucasLopesFrazao commented on frontend/frontendAngular/src/app/components/company-schedule/company-schedule.component.ts
> +import { GetUsersService } from 'src/app/services/get-users.service';
ok

2022-04-12 14:57 UTC, chaydson approved these changes

2022-04-15 21:45 UTC, PedroHenrique2077 approved these changes

2022-04-15 21:54 UTC, merged